// Posts
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POST_SUCCESS = ' GET_POST_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

// Users
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const USERNAME_INPUT = 'USERNAME_INPUT';
export const PASSWORD_INPUT = 'PASSWORD_INPUT';